# Top-level configuration for Acropolis omnibus process
# Bootstrap from Mithril and network sync, full ledger with BlockFrost API
# and history storage

# ============================================================================
# Startup Configuration
# ============================================================================
[global.startup]
network = "mainnet"
startup-mode = "genesis"
sync-mode = "mithril"
topic = "cardano.sequence.start"

# ============================================================================
# Bootstrap Module Configurations
# ============================================================================
[module.genesis-bootstrapper]

[module.mithril-snapshot-fetcher]
aggregator-url = "https://aggregator.release-mainnet.api.mithril.network/aggregator"
genesis-key = "5b3139312c36362c3134302c3138352c3133382c31312c3233372c3230372c3235302c3134342c32372c322c3138382c33302c31322c38312c3135352c3230342c31302c3137392c37352c32332c3133382c3139362c3231372c352c31342c32302c35372c37392c33392c3137365d"
# Download max age in hours. E.g. 8 means 8 hours (if there isn't any snapshot within this time range download from Mithril)
download-max-age = "never"
# Pause constraint E.g. "epoch:100", "block:1200"
pause = "none"
# Stop constraint likewise
stop = "none"

# ============================================================================
# Core Module Configurations
# ============================================================================
[module.peer-network-interface]
sync-point = "dynamic"
node-addresses = [
    "backbone.cardano.iog.io:3001",
    "backbone.mainnet.cardanofoundation.org:3001",
    "backbone.mainnet.emurgornd.com:3001",
]

[module.block-unpacker]
# Direct connection without consensus mediation
subscribe-topic = "cardano.block.available"

[module.tx-unpacker]
publish-utxo-deltas-topic = "cardano.utxo.deltas"
publish-asset-deltas-topic = "cardano.asset.deltas"
publish-withdrawals-topic = "cardano.withdrawals"
publish-certificates-topic = "cardano.certificates"
publish-governance-topic = "cardano.governance"
publish-block-txs-topic = "cardano.block.txs"
network-name = "mainnet"

[module.utxo-state]
address-delta-publish-mode = "compact"
address-delta-topic = "cardano.address.deltas"
block-totals-topic = "cardano.block.txs"

[module.spo-state]
block-subscribe-topic = "cardano.block.available"

# Enables /pools/{pool_id}/history endpoint, enables to query active_stakes
store-epochs-history = true
# Enable /pools/retired
store-retired-pools = true
# Enables /pools/{pool_id} endpoint
store-registration = true
# # Enables /pools/{pool_id}/updates endpoint
store-updates = true
# Enables /pools/{pool_id}/delegators endpoint (Requires store-stake-addresses to be enabled)
store-delegators = true
# Enables /pools/{pool_id}/votes endpoint
store-votes = true
# Store blocks, enables /pools/{pool_id}/blocks, /epochs/{number}/blocks/{pool_id}
store-blocks = true
# Store stake_addresses
store-stake-addresses = true

[module.spdd-state]
# Enables active_stakes in /epochs/latest | {number} endpoints
store-spdd = true

# Clear state on start up (default true)
clear-on-start = true

[module.drep-state]
# Enables /governance/dreps/{drep_id} endpoint (Requires store-delegators to be enabled)
store-info = true
# Enables /governance/dreps/{drep_id}/delegators endpoint
store-delegators = true
# Enables /governance/dreps/{drep_id}/metadata endpoint
store-metadata = true
# Enables /governance/dreps/{drep_id}/updates endpoint
store-updates = true
# Enables /governance/dreps/{drep_id}/votes endpoint
store-votes = true

[module.drdd-state]
store-drdd = true

[module.governance-state]
# Listen for DRep and SPO distributions
stake-drep-distribution-topic = "cardano.drep.distribution"
stake-spo-distribution-topic = "cardano.spo.distribution"

[module.parameters-state]
# Listen for governance actions
enact-state-topic = "cardano.enact.state"
store-history = true

[module.stake-delta-filter]
cache-mode = "predefined" # "predefined", "read", "write", "write-if-absent"
write-full-cache = "false"

[module.epochs-state]
block-subscribe-topic = "cardano.block.available"

[module.accounts-state]
# Optional subscription for when governance is active
drep-state-topic = "cardano.drep.state"

# Enable /epochs/{number}/stakes & /epochs/{number}/stakes/{pool_id} endpoints
spdd-retention-epochs = 1000
spdd-db-path = "./fjall-spdd"
spdd-clear-on-start = true
# Verify against captured CSV
verify-pots-file = "../../modules/accounts_state/test-data/pots.mainnet.csv"
verify-rewards-files = "../../modules/accounts_state/test-data/rewards.mainnet.{}.csv"
verify-spdd-files = "../../modules/accounts_state/test-data/spdd.mainnet.{}.csv"

[module.assets-state]
# Enables /assets endpoint
store-assets = true
# Enables /assets/{asset} endpoint (requires store-assets to be enabled)
store-info = true
# Enables /assets/{asset}/history endpoint
store-history = true
# Enables /assets/{asset}/transactions endpoint
#   Usage: "none", "all", or most recent: "1", "20", etc.
store-transactions = "none"
# Enables /assets/{asset}/addresses endpoint
store-addresses = true
# Enables /assets/{asset} endpoint (requires store-assets to be enabled)
index-by-policy = true

[module.chain-store]
# Clear state on start up (default true)
clear-on-start = true

[module.address-state]
# Clear state on start up (default true)
clear-on-start = true
# Enables /addresses/{address}, /addresses/{address}/extended,
# /addresses/{address}/utxos/{asset}, and /addresses/{address}/utxos endpoints
store-info = true
# Enables /addresses/{address}/totals endpoint
store-totals = true
# Enables /addresses/{address}/transactions endpoint
store-transactions = true

[module.historical-accounts-state]
# Clear state on start up (default true)
clear-on-start = true
# Enables /accounts/{stake_address}/rewards endpoint
store-rewards-history = true
# Enables /accounts/{stake_address}/history endpoint
store-active-stake-history = true
# Enables /accounts/{stake_address}/registrations endpoint
store-registration-history = true
# Enables /accounts/{stake_address}/delegations endpoint
store-delegation-history = true
# Enables /accounts/{stake_address}/mirs endpoint
store-mir-history = true
# Enables /accounts/{stake_address}/withdrawals endpoint
store-withdrawal-history = true
# Enables /accounts/{stake_address}/addresses endpoint
store-addresses = true
# Enables /accounts/{stake_address}/addresses/total endpoint (Requires store-addresses to be enabled)
store-tx-count = true

[module.historical-epochs-state]
blocks-subscribe-topic = "cardano.block.available"

[module.rest-blockfrost]

[module.rest-server]
address = "0.0.0.0"
port = 4340

[module.clock]

# ============================================================================
# Message Bus Configuration
# ============================================================================
[message-bus.internal]
class = "in-memory"

# Message routing
[[message-router.route]]  # Everything is internal only
pattern = "#"
bus = "internal"
