# Top-level configuration for Acropolis omnibus process
# Bootstrap from Mithril and network sync, with full ledger and
# block validation

# ============================================================================
# Startup Configuration
# ============================================================================
[global.startup]
startup-mode = "genesis"
sync-mode = "mithril"
topic = "cardano.sequence.start"

# ============================================================================
# Bootstrap Module Configurations
# ============================================================================
[module.genesis-bootstrapper]

[module.mithril-snapshot-fetcher]
aggregator-url = "https://aggregator.release-mainnet.api.mithril.network/aggregator"
genesis-key = "5b3139312c36362c3134302c3138352c3133382c31312c3233372c3230372c3235302c3134342c32372c322c3138382c33302c31322c38312c3135352c3230342c31302c3137392c37352c32332c3133382c3139362c3231372c352c31342c32302c35372c37392c33392c3137365d"
# Download max age in hours. E.g. 8 means 8 hours (if there isn't any snapshot within this time range download from Mithril)
download-max-age = "never"
# Pause constraint E.g. "epoch:100", "block:1200"
pause = "none"

# ============================================================================
# Core Module Configurations
# ============================================================================
[module.peer-network-interface]
sync-point = "dynamic"
node-addresses = [
    "backbone.cardano.iog.io:3001",
    "backbone.mainnet.cardanofoundation.org:3001",
    "backbone.mainnet.emurgornd.com:3001",
]
magic-number = 764824073

[module.consensus]
# List of validation result topics to listen on
validators = [
           "cardano.validation.tx",
           "cardano.validation.vrf",
           "cardano.validation.kes",
           "cardano.validation.governance",
           "cardano.validation.spo",
           "cardano.validation.accounts",
           "cardano.validation.utxo",
           # TODO more
]

[module.block-unpacker]

[module.tx-unpacker]
# Subscriptions needed for validation
bootstrapped-subscribe-topic = "cardano.sequence.bootstrapped"
protocol-parameters-subscribe-topic = "cardano.protocol.parameters"

publish-utxo-deltas-topic = "cardano.utxo.deltas"
publish-withdrawals-topic = "cardano.withdrawals"
publish-certificates-topic = "cardano.certificates"
publish-governance-topic = "cardano.governance"
publish-block-txs-topic = "cardano.block.txs"
publish-tx-validation-topic = "cardano.validation.tx"
network-name = "mainnet"

[module.utxo-state]
address-delta-topic = "cardano.address.deltas"
block-totals-topic = "cardano.block.txs"
pool-registration-updates-subscribe-topic = "cardano.pool.registration.updates"
stake-registration-updates-subscribe-topic = "cardano.stake.registration.updates"

[module.spo-state]

[module.stake-delta-filter]

[module.epochs-state]

[module.parameters-state]
enact-state-topic = "cardano.enact.state"

[module.drep-state]

[module.governance-state]
# Listen for DRep and SPO distributions
stake-drep-distribution-topic = "cardano.drep.distribution"
stake-spo-distribution-topic = "cardano.spo.distribution"

[module.accounts-state]
# Optional subscription for when governance is active
drep-state-topic = "cardano.drep.state"

verify-pots-file = "../../modules/accounts_state/test-data/pots.mainnet.csv"
verify-rewards-files = "../../modules/accounts_state/test-data/rewards.mainnet.{}.csv"
verify-spdd-files = "../../modules/accounts_state/test-data/spdd.mainnet.{}.csv"

[module.block-vrf-validator]

[module.block-kes-validator]

[module.clock]

# ============================================================================
# Message Bus Configuration
# ============================================================================
[message-bus.internal]
class = "in-memory"

# Message routing
[[message-router.route]]  # Everything is internal only
pattern = "#"
bus = "internal"
