# Acropolis Governance state module

[package]
name = "acropolis_module_tx_validator_phase1"
version = "0.1.0"
edition = "2021"
authors = ["Dmitry Shtukenberg <dmitry.shtukenberg@iohk.io>"]
description = "Transaction validator, phase 1"
license = "Apache-2.0"

[dependencies]
acropolis_common = { path = "../../common" }
acropolis_codec = { path = "../../codec" }

caryatid_sdk = { workspace = true }

anyhow = { workspace = true }
async-trait = "0.1"
config = { workspace = true }
csv = "1"
hex = { workspace = true }
pallas = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true, features = ["base64"] }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.20", features = ["registry", "env-filter"] }

[lib]
path = "src/tx_validator_phase1.rs"
