# Acropolis Governance state module

[package]
name = "acropolis_module_tx_validator_phase1"
version = "0.1.0"
edition = "2021"
authors = ["Dmitry Shtukenberg <dmitry.shtukenberg@iohk.io>"]
description = "Transaction validator, phase 1"
license = "Apache-2.0"

[dependencies]
acropolis_common = { path = "../../common" }
acropolis_codec = { path = "../../codec" }

caryatid_sdk = { workspace = true }
anyhow = { workspace = true }
config = { workspace = true }
pallas = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[lib]
path = "src/tx_validator_phase1.rs"
