# The topic to publish sync commands on
sync-command-publisher-topic = "cardano.sync.command"
# The topic to signal readiness for the indexer to request sync
genesis-complete-topic = "cardano.sequence.bootstrapped"
# The topic to receive txs on
txs-subscribe-topic = "cardano.txs"