# The topic to publish blocks on
block-topic = "cardano.block.available"
# The topic to wait for when listening for genesis values from another module
genesis-completion-topic = "cardano.sequence.bootstrapped"
# The topic to listen on for runtime sync commands
sync-command-topic = "cardano.sync.command"

# Upstream node connections
node-addresses = [
    "backbone.cardano.iog.io:3001",
    "backbone.mainnet.cardanofoundation.org:3001",
    "backbone.mainnet.emurgornd.com:3001",
]

# The initial point to start syncing from. Options:
# - "origin": sync from the very start of the chain
# - "tip": sync from the very end of the chain
# - "cache": replay messages from a local filesystem cache, then sync from the point right after that cache.
# - "dynamic": awaits a sync command to begin fetching blocks, can change sync point at runtime.
sync-point = "dynamic"
# The cache dir to use when sync-point is "cache"
cache-dir = "upstream-cache"

# Block flow mode determines how blocks are synchronized:
# - direct: blocks are auto-fetched as announced, peer-network-interface handles the full flow.
# - consensus: block headers are published as offers and are only fetched when consensus sends back a BlockWanted message.
block-flow-mode = "consensus"

# The consensus module subscribes to this to receive block announcements
consensus-topic = "cardano.consensus.offers"

# The consensus module publishes to this to request specific blocks be fetched
block-wanted-topic = "cardano.consensus.wants"
