# Acropolis testing process
[package]
name = "acropolis_process_testing"
version = "0.1.0"
edition = "2021"
authors = ["Josh Marchand <josh@sundae.fi>"]
description = "Acropolis testing process to run end to end tests"
license = "Apache-2.0"

[dependencies]
acropolis_common = { path = "../../common" }
acropolis_module_snapshot_bootstrapper = { path = "../../modules/snapshot_bootstrapper" }
acropolis_module_tx_unpacker = { path = "../../modules/tx_unpacker" }
acropolis_module_spo_state = { path = "../../modules/spo_state" }

caryatid_process = { workspace = true }
caryatid_sdk = { workspace = true }

anyhow = { workspace = true }
config = { workspace = true }
tokio = { workspace = true }
hex = { workspace = true }
